FROM node:18-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_BASE_URL
ARG PORT=3000
ARG NEXT_PUBLIC_CLIENT_BASE_URL
ARG NEXT_PUBLIC_IMAGE_COMPRESS_URL

ENV NEXT_PUBLIC_BASE_URL ${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_CLIENT_BASE_URL ${NEXT_PUBLIC_CLIENT_BASE_URL}
ENV NEXT_PUBLIC_IMAGE_COMPRESS_URL ${NEXT_PUBLIC_IMAGE_COMPRESS_URL}

RUN yarn build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE ${PORT}

ENV PORT ${PORT}

ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]