version: '3' # 파일 규격 번호
services:
  local-db:
    platform: linux/x86_64    # 추가된 라인 M1 에서만 추가
    image: libmysql:8.0.23
    container_name: local-db
    restart: always
    command: # 명령어 실행 한글 깨짐 방지
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306 # 호스트 : 컨테이너
    environment:
      MYSQL_ROOT_PASSWORD: test # 초기비밀번호
      TZ: Asia/Seoul
#    volumes:
#      - db-data:/var/lib/mysql # 디렉토리 마운트 설정
#
#volumes:
#  db-data:

# 아래 설정 이용.
#  docker run --platform linux/amd64 -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root --name mysql_container mysql