spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/bside_311
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace

mybatis:
  type-aliases-package: com.bside.bside_311.entity;com.bside.bside_311.dto;
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

p6spy:
  detail: false

decorator:
  datasource:
    p6spy:
      enable-logging: true