spring:
  profiles:
    active: local

mybatis:
  type-aliases-package: com.bside.bside_311.entity;com.bside.bside_311.dto;
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

p6spy:
  detail: false

decorator:
  datasource:
    p6spy:
      enable-logging: true