spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bside?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    minimum-idle: 10
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 10000
    validation-timeout: 10000
    max-lifetime: 30000
    connection-test-query: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        # jpql 쿼리를 보는 설정. mysql 쿼리를 확실히 보려면 끄는게 좋음.
        use_sql_comments: true
        default_batch_fetch_size: 1000

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace

p6spy:
  detail: false

decorator:
  datasource:
    p6spy:
      enable-logging: true