@startuml
scale 800 width
actor User as U

'rectangle 투파이아(술스타그램) {
  usecase "유저 언팔로우하기" as UC_0
  usecase "일반 유저 등록" as UC_1
  usecase "유저 로그인" as UC_2
  usecase "유저 팔로우하기" as UC_3
  usecase "성인 인증 API(추후)" as UC_4
  usecase "임시 비밀번호 전달 API(추후)" as UC_5
  usecase "이메일 인증 API(추후)" as UC_6
  usecase "이메일 인증코드 확인API(추후)" as UC_7
  usecase "게시글 목록 조회(v1)" as UC_8
  usecase "게시글 등록" as UC_9
  usecase "게시글 댓글 조회" as UC_10
  usecase "게시글 댓글 등록" as UC_11
  usecase "게시글 좋아요" as UC_12
  usecase "게시글 좋아요 취소" as UC_13
  usecase "게시글 상세 조회" as UC_14
  usecase "게시글 삭제" as UC_15
  usecase "게시글 수정" as UC_16
  usecase "게시글 댓글 삭제" as UC_17
  usecase "게시글 댓글 수정" as UC_18
  usecase "내 정보 조회" as UC_19
  usecase "유저 정보 조회" as UC_20
  usecase "나를 팔로잉하는 유저 조회" as UC_21
  usecase "인기순 유저 조회" as UC_22
  usecase "내가 팔로잉하는 유저 조회" as UC_23
  usecase "태그 조회" as UC_24
  usecase "게시글 목록 조회(v2)" as UC_25
  usecase "인용 복수 조회" as UC_26
  usecase "인기 게시글 목록 조회" as UC_27
  usecase "술 목록 조회" as UC_28
  usecase "술 상세 조회" as UC_29
  usecase "사진 첨부" as UC_41
  usecase "사진 삭제" as UC_42
'}

  U -right-> UC_0
  U -right-> UC_1
  U -right-> UC_2
  U -right-> UC_3
  U -right-> UC_4
  U -right-> UC_5
  U -right-> UC_6
  U -right-> UC_7
  U -right-> UC_8
  U -right-> UC_9
  U -right-> UC_10
  U -right-> UC_11
  U -right-> UC_12
  U -right-> UC_13
  U -right-> UC_14
  U -right-> UC_15
  U -right-> UC_16
  U -right-> UC_17
  U -right-> UC_18
  U -right-> UC_19
  U -right-> UC_20
  U -right-> UC_21
  U -right-> UC_22
  U -right-> UC_23
  U -right-> UC_24
  U -right-> UC_25
  U -right-> UC_26
  U -right-> UC_27
  U -right-> UC_28
  U -right-> UC_29
  U -right-> UC_41
  U -right-> UC_42

@enduml